### ISSUE TITLE
bypassing on client ?

### ISSUE THREAD

**Issue by ZuherLaith** [st4ckh0und/XignCode3-bypass#8]
I've noticed that this bypass outputs a dll for the game client,
my game client is hooked with the original xigncode (x3.xem ...etc)

so, how to do this?
do I need to hook **XignCode Client.dll** to my **game exe**? or something else?,

**Comment by zeffy** [comment]
@ZuherLaith just rename `XignCode Client.dll` to `x3.xem` and it will work.

**Comment by dandy1990** [comment]
@zeffy 大佬你好 能教我使用这个XignCode3-bypass吗 可以有偿 方便加一下你的qq吗
